# Generated by Django 2.2.3 on 2019-10-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain_name', models.CharField(max_length=100)),
                ('grain_type', models.CharField(max_length=100)),
                ('grain_price', models.CharField(max_length=100)),
            ],
        ),
    ]
