# Generated by Django 2.2.3 on 2019-10-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmeasy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GrainName', models.CharField(max_length=100)),
                ('GrainType', models.CharField(max_length=100)),
                ('date', models.DateField(default='2019-10-05')),
                ('GrainPrice', models.CharField(max_length=100)),
                ('image', models.ImageField(default='None', upload_to='images/')),
            ],
        ),
    ]
