# Generated by Django 2.2.3 on 2019-10-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmeasy', '0002_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='image',
        ),
    ]
