# Generated by Django 2.2.3 on 2019-10-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmeasy', '0003_auto_20191005_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='GrainImage',
            field=models.ImageField(default='None', upload_to='images/'),
        ),
    ]
